# Generated by Django 2.0.2 on 2019-01-30 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('big_brother', '0002_actiontoken_temporarytoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(verbose_name='Success')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Execution date')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('url', models.URLField(max_length=400, verbose_name='URL')),
                ('script', models.TextField(max_length=4000, verbose_name='Script')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='big_brother.Application')),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='big_brother.TestType'),
        ),
        migrations.AddField(
            model_name='execution',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='big_brother.Test'),
        ),
    ]
